### PR TITLE
ignore .ts in npmignore

### LINKED ISSUE #21: Dont publish .ts file to npm
Could you please just publish the .js and .d.ts file to npm?
Otherwise we always get this error:

> Module build failed: Error: d:\Development\git\futura-connectivity\src\Opten.FuturaConnectivity.Web.UI.Client\node_modules\ng-autosize\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

You can just add a `.npmignore` whit this content:
```
*.ts
!*.d.ts
```

### PR DESCRIPTION
**Pull request by wiedikerli**
closes #21 and #12

### CODE REVIEW

**Comment by alastairparagas** [comment]
Is there any status on when this pull request will be merged in?

**Comment by leegreenwood** [comment]
I'd really like this merged in - is causing me no end of brief trying to get a build completed.

**Comment by shyamal890** [comment]
+1

**Comment by shyamal890** [comment]
@stevepapa

**Pull request closed without merging**
